// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OlivarBackend.Data;

#nullable disable

namespace OlivarBackend.Migrations
{
    [DbContext(typeof(RestauranteDbContext))]
    partial class RestauranteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OlivarBackend.Models.Banner", b =>
                {
                    b.Property<int>("BannerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BannerId"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Titulo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BannerId")
                        .HasName("PK__Banners__32E86AD142C2F01D");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("OlivarBackend.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoriaId")
                        .HasName("PK__Categori__F353C1E57F62D38E");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("OlivarBackend.Models.ComentariosProducto", b =>
                {
                    b.Property<int>("ComentarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComentarioId"));

                    b.Property<int?>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ComentarioId")
                        .HasName("PK__Comentar__F1844938BC5623BD");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ComentariosProductos");
                });

            modelBuilder.Entity("OlivarBackend.Models.Configuracion", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Valor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Clave")
                        .HasName("PK__Configur__E8181E10ED89AB4F");

                    b.ToTable("Configuracion", (string)null);
                });

            modelBuilder.Entity("OlivarBackend.Models.Consulta", b =>
                {
                    b.Property<int>("ConsultaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultaId"));

                    b.Property<string>("Asunto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ConsultaId")
                        .HasName("PK__Consulta__7D0B7DCC153EF9C3");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("OlivarBackend.Models.Cupone", b =>
                {
                    b.Property<int>("CuponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuponId"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("DescuentoPorcentaje")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.HasKey("CuponId")
                        .HasName("PK__Cupones__C4356897D86D66B5");

                    b.HasIndex(new[] { "Codigo" }, "UQ__Cupones__06370DAC9A3337F4")
                        .IsUnique()
                        .HasFilter("[Codigo] IS NOT NULL");

                    b.ToTable("Cupones");
                });

            modelBuilder.Entity("OlivarBackend.Models.DetallePedido", b =>
                {
                    b.Property<int>("DetallePedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetallePedidoId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("DetallePedidoId")
                        .HasName("PK__DetalleP__6ED21C21B91B4040");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallePedidos");
                });

            modelBuilder.Entity("OlivarBackend.Models.DireccionesEntrega", b =>
                {
                    b.Property<int>("DireccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DireccionId"));

                    b.Property<bool?>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Distrito")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("Latitud")
                        .HasColumnType("float");

                    b.Property<double?>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Referencia")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("DireccionId")
                        .HasName("PK__Direccio__68906D645C8AE0B1");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DireccionesEntrega", (string)null);
                });

            modelBuilder.Entity("OlivarBackend.Models.Factura", b =>
                {
                    b.Property<int>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturaId"));

                    b.Property<string>("DireccionFiscal")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("MontoTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Ruc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RUC");

                    b.HasKey("FacturaId")
                        .HasName("PK__Facturas__5C024865B887FD28");

                    b.HasIndex("PedidoId");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("OlivarBackend.Models.HistorialEstadoPedido", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"));

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.HasKey("EstadoId")
                        .HasName("PK__Historia__FEF86B00D17E9BA1");

                    b.HasIndex("PedidoId");

                    b.ToTable("HistorialEstadoPedido", (string)null);
                });

            modelBuilder.Entity("OlivarBackend.Models.ImagenesProducto", b =>
                {
                    b.Property<int>("ImagenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImagenId"));

                    b.Property<bool?>("EsPrincipal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ImagenId")
                        .HasName("PK__Imagenes__0C7D20B780CC0D26");

                    b.HasIndex("ProductoId");

                    b.ToTable("ImagenesProducto", (string)null);
                });

            modelBuilder.Entity("OlivarBackend.Models.LogsSistema", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Accion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TablaAfectada")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("LogId")
                        .HasName("PK__LogsSist__5E548648C784FC70");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogsSistema", (string)null);
                });

            modelBuilder.Entity("OlivarBackend.Models.Notificacione", b =>
                {
                    b.Property<int>("NotificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificacionId"));

                    b.Property<DateTime?>("FechaEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("Leida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Mensaje")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Titulo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("NotificacionId")
                        .HasName("PK__Notifica__BCC120243920B53E");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("OlivarBackend.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<DateTime?>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Metodo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.HasKey("PagoId")
                        .HasName("PK__Pagos__F00B61381DD95361");

                    b.HasIndex("PedidoId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("OlivarBackend.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoId"));

                    b.Property<int?>("CuponId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DescuentoAplicado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MetodoEntrega")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Delivery");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("PedidoId")
                        .HasName("PK__Pedidos__09BA1430CD026C3C");

                    b.HasIndex("CuponId");

                    b.HasIndex("SucursalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("OlivarBackend.Models.Permiso", b =>
                {
                    b.Property<int>("PermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermisoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PermisoId")
                        .HasName("PK__Permisos__96E0C723C3DFD14A");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("OlivarBackend.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ProductoId")
                        .HasName("PK__Producto__A430AEA3C28F4034");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("OlivarBackend.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"));

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ReservaId")
                        .HasName("PK__Reservas__C3993763E41E628E");

                    b.HasIndex("SucursalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("OlivarBackend.Models.RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolPermiso", (string)null);
                });

            modelBuilder.Entity("OlivarBackend.Models.Role", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId")
                        .HasName("PK__Roles__F92302F1596FD51F");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Roles__75E3EFCF7F496BC6")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("OlivarBackend.Models.Sucursale", b =>
                {
                    b.Property<int>("SucursalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SucursalId"));

                    b.Property<bool?>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SucursalId")
                        .HasName("PK__Sucursal__6CB482E1DF4939D8");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("OlivarBackend.Models.Suscriptore", b =>
                {
                    b.Property<int>("SuscriptorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuscriptorId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("SuscriptorId")
                        .HasName("PK__Suscript__03ED70B24674BBFE");

                    b.HasIndex(new[] { "Email" }, "UQ__Suscript__A9D10534A5E7D865")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Suscriptores");
                });

            modelBuilder.Entity("OlivarBackend.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("TokenExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenRecuperacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId")
                        .HasName("PK__Usuarios__2B3DE7B8C5D631BF");

                    b.HasIndex("RolId");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuarios__A9D1053482EAC8B3")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PermisoRole", b =>
                {
                    b.Property<int>("PermisosPermisoId")
                        .HasColumnType("int");

                    b.Property<int>("RolsRolId")
                        .HasColumnType("int");

                    b.HasKey("PermisosPermisoId", "RolsRolId");

                    b.HasIndex("RolsRolId");

                    b.ToTable("PermisoRole");
                });

            modelBuilder.Entity("OlivarBackend.Models.ComentariosProducto", b =>
                {
                    b.HasOne("OlivarBackend.Models.Producto", "Producto")
                        .WithMany("ComentariosProductos")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK__Comentari__Produ__76969D2E");

                    b.HasOne("OlivarBackend.Models.Usuario", "Usuario")
                        .WithMany("ComentariosProductos")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Comentari__Usuar__75A278F5");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OlivarBackend.Models.Consulta", b =>
                {
                    b.HasOne("OlivarBackend.Models.Usuario", "Usuario")
                        .WithMany("Consulta")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Consultas__Usuar__00200768");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OlivarBackend.Models.DetallePedido", b =>
                {
                    b.HasOne("OlivarBackend.Models.Pedido", "Pedido")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("PedidoId")
                        .IsRequired()
                        .HasConstraintName("FK__DetallePe__Pedid__68487DD7");

                    b.HasOne("OlivarBackend.Models.Producto", "Producto")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK__DetallePe__Produ__693CA210");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("OlivarBackend.Models.DireccionesEntrega", b =>
                {
                    b.HasOne("OlivarBackend.Models.Usuario", "Usuario")
                        .WithMany("DireccionesEntregas")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Direccion__Usuar__52593CB8");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OlivarBackend.Models.Factura", b =>
                {
                    b.HasOne("OlivarBackend.Models.Pedido", "Pedido")
                        .WithMany("Facturas")
                        .HasForeignKey("PedidoId")
                        .IsRequired()
                        .HasConstraintName("FK__Facturas__Pedido__03F0984C");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("OlivarBackend.Models.HistorialEstadoPedido", b =>
                {
                    b.HasOne("OlivarBackend.Models.Pedido", "Pedido")
                        .WithMany("HistorialEstadoPedidos")
                        .HasForeignKey("PedidoId")
                        .IsRequired()
                        .HasConstraintName("FK__Historial__Pedid__6D0D32F4");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("OlivarBackend.Models.ImagenesProducto", b =>
                {
                    b.HasOne("OlivarBackend.Models.Producto", "Producto")
                        .WithMany("ImagenesProductos")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK__ImagenesP__Produ__4BAC3F29");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("OlivarBackend.Models.LogsSistema", b =>
                {
                    b.HasOne("OlivarBackend.Models.Usuario", "Usuario")
                        .WithMany("LogsSistemas")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__LogsSiste__Usuar__07C12930");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OlivarBackend.Models.Notificacione", b =>
                {
                    b.HasOne("OlivarBackend.Models.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__Notificac__Usuar__7B5B524B");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OlivarBackend.Models.Pago", b =>
                {
                    b.HasOne("OlivarBackend.Models.Pedido", "Pedido")
                        .WithMany("Pagos")
                        .HasForeignKey("PedidoId")
                        .IsRequired()
                        .HasConstraintName("FK__Pagos__PedidoId__70DDC3D8");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("OlivarBackend.Models.Pedido", b =>
                {
                    b.HasOne("OlivarBackend.Models.Cupone", "Cupon")
                        .WithMany("Pedidos")
                        .HasForeignKey("CuponId")
                        .HasConstraintName("FK__Pedidos__CuponId__6477ECF3");

                    b.HasOne("OlivarBackend.Models.Sucursale", "Sucursal")
                        .WithMany("Pedidos")
                        .HasForeignKey("SucursalId")
                        .HasConstraintName("FK__Pedidos__Sucursa__656C112C");

                    b.HasOne("OlivarBackend.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Pedidos__Usuario__6383C8BA");

                    b.Navigation("Cupon");

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OlivarBackend.Models.Producto", b =>
                {
                    b.HasOne("OlivarBackend.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK__Productos__Categ__47DBAE45");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("OlivarBackend.Models.Reserva", b =>
                {
                    b.HasOne("OlivarBackend.Models.Sucursale", "Sucursal")
                        .WithMany("Reservas")
                        .HasForeignKey("SucursalId")
                        .HasConstraintName("FK__Reservas__Sucurs__5812160E");

                    b.HasOne("OlivarBackend.Models.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Reservas__Usuari__571DF1D5");

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OlivarBackend.Models.RolPermiso", b =>
                {
                    b.HasOne("OlivarBackend.Models.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .IsRequired()
                        .HasConstraintName("FK_RolPermiso_Permiso");

                    b.HasOne("OlivarBackend.Models.Role", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_RolPermiso_Rol");

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("OlivarBackend.Models.Usuario", b =>
                {
                    b.HasOne("OlivarBackend.Models.Role", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .HasConstraintName("FK__Usuarios__RolId__4222D4EF");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PermisoRole", b =>
                {
                    b.HasOne("OlivarBackend.Models.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisosPermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlivarBackend.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolsRolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OlivarBackend.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("OlivarBackend.Models.Cupone", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("OlivarBackend.Models.Pedido", b =>
                {
                    b.Navigation("DetallePedidos");

                    b.Navigation("Facturas");

                    b.Navigation("HistorialEstadoPedidos");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("OlivarBackend.Models.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("OlivarBackend.Models.Producto", b =>
                {
                    b.Navigation("ComentariosProductos");

                    b.Navigation("DetallePedidos");

                    b.Navigation("ImagenesProductos");
                });

            modelBuilder.Entity("OlivarBackend.Models.Role", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("OlivarBackend.Models.Sucursale", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("OlivarBackend.Models.Usuario", b =>
                {
                    b.Navigation("ComentariosProductos");

                    b.Navigation("Consulta");

                    b.Navigation("DireccionesEntregas");

                    b.Navigation("LogsSistemas");

                    b.Navigation("Notificaciones");

                    b.Navigation("Pedidos");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
